[package]
name = "aoc-2015-07"
version = "0.1.0"
authors = ["Svetlin Zarev <svetlin.zarev@zarev.net>"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
aoc-2015-common = { path = "../aoc-2015-common" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
