[package]
name = "aoc-2019"
version = "0.1.0"
authors = ["Svetlin Zarev <svetlin.zarev@zarev.net>"]
edition = "2018"

[[bin]]
name = "aoc"

[dependencies]
aoc-2019-common = {path = "../aoc-2019-common"}
aoc-2019-01 = { path = "../aoc-2019-01" }
