[package]
name = "aoc-2016-01"
version = "0.1.0"
authors = ["Svetlin Zarev <svetlin.zarev@zarev.net>"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
aoc-2016-common = { path = "../aoc-2016-common" }
anyhow = "1"
